export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_MOBILES_PENDING = 'REQUEST_MOBILES_PENDING';
export const REQUEST_MOBILES_SUCCESS = 'REQUEST_MOBILES_SUCCESS';
export const REQUEST_MOBILES_FAILED = 'REQUEST_MOBILES_FAILED';
